### ISSUE TITLE
Bidirectional synchronization

### ISSUE THREAD

**Issue by hiroshiyui** [KKBOX/redmine-trello-card-sync#11]
Currently this plug-in is doing one-way synchronization from Redmine to Trello. Furtherly we need bidirectional synchronization.

**Comment by seb-sykio** [comment]
any roadmap ?

**Comment by hiroshiyui** [comment]
I can't guarantee, I will do it recently in my 40% work time, though.

**Comment by hiroshiyui** [comment]
done in #18
