### ISSUE TITLE
Error after plugin install

### ISSUE THREAD

**Issue by ghost** [KKBOX/redmine-trello-card-sync#12]
Hi,

After I installed plugin I can't use Redmine anymore. Ever login page gives me error internal error.
I'm attaching log for you with error.
[redmine.log](https://github.com/KKBOX/redmine-trello-card-sync/files/1386331/redmine.log)

My Environment :
Centos 6.9
MySQL 5.1.73-8.el6_8
HTTPD 2.2.15-60.el6.centos.5
Ruby 2.4.0
Ruby Passanger 5.1.8
Redmine 3.4

If you need any other informations just ask.

**Comment by hiroshiyui** [comment]
Hello,

I can't reproduce your situation, do you follow Setup steps to install gems & run DB migrations?
