### ISSUE TITLE
migration issue with mysql

### ISSUE THREAD

**Issue by seb-sykio** [KKBOX/redmine-trello-card-sync#16]
Mysql2::Error: BLOB/TEXT column 'trello_excluded_trackers' can't have a default value: ALTER TABLE `projects` CHANGE `trello_excluded_trackers` `trello_excluded_trackers` text DEFAULT '[]'

redmine/plugins/redmine_trello_card_sync/db/migrate/005_change_trello_exclude_tracker_default_to_project.rb:3:in `change'

https://bugs.mysql.com/bug.php?id=21532

**Comment by hiroshiyui** [comment]
Hi @seb-sykio I've changed the related DB migrations for MySQL compatibility, please give the latest release 1.0.1 a try.

**Comment by seb-sykio** [comment]
thanks a lot. working well.
little thing also : Note: The rake task db:migrate_plugins has been deprecated, please use the replacement version redmine:plugins:migrate

and one question : the sync only work from redmine to trello, but not from trello to redmine, is that correct ?

**Comment by hiroshiyui** [comment]
Hello @seb-sykio,

Thanks, I will correct document about plugin DB migration in next release. And bidirectional sync is in progress, you may follow #11 for the updates.
