### ISSUE TITLE
500 error from incorrect key

### ISSUE THREAD

**Issue by mafuchi** [KKBOX/redmine-trello-card-sync#19]
I was able to successfully install the plugin, but when I accidently saved the redmine/admin/plugins/redmine-trello-card-sync page before inputting all the keys correctly I got a 500 error when trying to access this page.  

I have removed the plugin (migrated and deleted from disk) and reinstalled, the issue persists.  I can not find a way to change the key so it won't give me this error.  

I've added log info for reference.

`Started GET "/redmine/settings/plugin/redmine_trello_card_sync" for 127.0.0.1 at 2018-03-21 12:19:52 -0700`
`Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_trello_card_sync"}`
`Settings cache cleared.
  Current user: admin (id=1)
  Rendered plugins/redmine_trello_card_sync/app/views/settings/_webhook_settings.html.erb (191.4ms)
  Rendered plugins/redmine_trello_card_sync/app/views/settings/_trello_sync_settings.html.erb (191.4ms)
  Rendered settings/plugin.html.erb within layouts/admin (191.9ms)
Completed 500 Internal Server Error in 198ms (ActiveRecord: 1.0ms)`
`
ActionView::Template::Error (Cannot GET /1/tokens/?key=[replaced key]&token=&webhooks=true):
     9: </p>
    10: <h2>Registered Webhooks</h2>
    11:   <ul>
    12:     <% TrelloWebhooksHelper.list_webhooks.each do |webhook| %>
    13:     <li><em><%= webhook['id'] %></em> - <%= webhook['description'] %> -> <%= webhook['callbackURL'] %></li>
    14:     <%end %>
    15:   </ul>`

**Environment**:
  Redmine version                3.4.4.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-mingw32]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
**SCM**:
  Subversion                     1.9.5
  Git                            2.14.1
  Filesystem                     
**Redmine plugins:**
  redmine_agile                  1.4.6
  redmine_custom_css             0.1.7
  redmine_trello_card_sync       1.1.0

**Comment by hiroshiyui** [comment]
@mafuchi please give v1.1.1 a try.

**Comment by mafuchi** [comment]
Thanks for the update.  This did indeed fix the issue.  Though I am still having trouble getting a two-way communication going.
I entered the keys and Tokens as requested, but for the Trello Webhooks Endpoint URL, I created a dynamic DNS (since my server is on my home PC).  I'm not sure if this is correct.  Anyways I am still getting an error.
`Started GET "/redmine/projects/git-scripts/trello_card_sync/mappings" for 127.0.0.1 at 2018-03-22 13:40:00 -0700`
`Processing by MappingsController#index as HTML
  Parameters: {"project_id"=>"git-scripts"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 152ms (ActiveRecord: 63.1ms)"`
`
"TypeError (no implicit conversion of nil into String):
  plugins/redmine_trello_card_sync/app/controllers/mappings_controller.rb:93:in "excluded_trackers"
  plugins/redmine_trello_card_sync/app/controllers/mappings_controller.rb:20:in "index"
  lib/redmine/sudo_mode.rb:63:in "sudo_mode"
`
![developer api keys](https://user-images.githubusercontent.com/6242892/37797403-f70fb9b0-2dd6-11e8-9d0e-1f764d37cedb.png)
![oath](https://user-images.githubusercontent.com/6242892/37797404-f7267a10-2dd6-11e8-8fc9-49ee15d2cb7c.png)
My dynmaic DNS syntax:
`mydynamicdnsaddress.com/redmine/trello_webhooks.json`

Any assistance would be apprieciated.

**Comment by hiroshiyui** [comment]
Hello @mafuchi, did you ran `rake redmine:plugins:migrate` before?

**Comment by hiroshiyui** [comment]
@mafuchi please give v1.1.2 a try.

**Comment by mafuchi** [comment]
To uninstall and install I did the following:
- `bundle exec rake db:migrate:plugin NAME=redmine_trello_card_sync VERSION=0 RAILS_ENV=production`
- I deleted the folder in plugins
- `git clone https://github.com/KKBOX/redmine-trello-card-sync.git redmine_trello_card_sync`
- `bundle install --without development test`
- `bundle exec rake db:migrate_plugins RAILS_ENV=production`
- Restart Server

I have updated my file, but I am now getting a different error:
`Started GET "/redmine/projects/git-scripts/wiki" for 127.0.0.1 at 2018-03-23 12:41:27 -0700`
`Processing by WikiController#show as HTML`
`  Parameters: {"project_id"=>"git-scripts"}`
`  Current user: admin (id=1)`
`  Rendered attachments/_form.html.erb (127.1ms)`
`  Rendered wiki/edit.html.erb within layouts/base (372.4ms)`
`[Trello] Is TrelloCardSync plugin ready? true`
`  Rendered inline template (1.0ms)`
`Completed 200 OK in 20136ms (Views: 19838.5ms | ActiveRecord: 219.5ms)`
`Started GET "/redmine/projects/git-scripts/trello_card_sync/mappings" for 127.0.0.1 at 2018-03-23` `12:41:56 -0700`
`Processing by MappingsController#index as HTML`
`  Parameters: {"project_id"=>"git-scripts"}`
`  Current user: admin (id=1)`
`Completed 500 Internal Server Error in 7ms (ActiveRecord: 2.4ms)`

`NoMethodError (undefined method 'reject' for nil:NilClass):`
`  plugins/redmine_trello_card_sync/app/controllers/mappings_controller.rb:107:in 'excluded_trackers_v2'`
`  plugins/redmine_trello_card_sync/app/controllers/mappings_controller.rb:21:in 'index'`
`  lib/redmine/sudo_mode.rb:63:in 'sudo_mode'`

**Comment by hiroshiyui** [comment]
@mafuchi sorry for the inconvenience, please give v1.1.3 a try. 🙇

**Comment by hiroshiyui** [comment]
@mafuchi does v1.1.3 work for you? I have to say sorry again that this plugin is mainly for my office team collaboration, features of this plugin are not well tested for other installations. Your feedback is very important for me to make this plugin better.

**Comment by mafuchi** [comment]
@hiroshiyui Sorry for the delay.  No need for apologies, you have gone above and beyond in my opinion.
The update did fix the issue I was having, but attempting a bi-directional sync returns a 403 error.  
`[Trello] Oops! Failed to register the webhook: URL (http://foo.bar.com/redmine/trello_webhooks.json) did not return 200 status code, got 403`
I wanted to wait and do more testing before writing back.  I'm not sure if this is an https issue (as I don't have an SSL cert for my home ddns).  I can definitely access the webhooks url from different networks. Though it only returns this:
`{
status: "ok"
}`

Let me know if there is anything you think I should try.
Cheers!

**Comment by hiroshiyui** [comment]
@mafuchi Thanks for the feedback. I need your logs from the `[Trello] Creating webhook for ...` line to the error backtrace.

BTW it doesn't matter if you are using http or https, and if you get a `{ status: "ok" }` while doing a HTTP GET request, it means that you have a valid webhook URL.

**Comment by mafuchi** [comment]
`Started PATCH "/redmine/projects/git-scripts/trello_card_sync/mappings/save" for 127.0.0.1 at 2018-03-26 17:29:24 -0700`

`Processing by MappingsController#save as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"foobar==", "project"=>{"trello_board_id"=>"id_1", "trello_enable_bidirectional_sync"=>"1", "trello_excluded_trackers"=>[""]}, "trello_list_mapping"=>{"1"=>"id_2", "2"=>"", "3"=>"", "4"=>"", "5"=>"id_3", "6"=>""}, "commit"=>"Save changes", "project_id"=>"git-scripts"}
  Current user: admin (id=1)`

`[Trello] Bidirectional sync is enabled
[Trello] Creating webhook for 'Script clean up' (id_1)
[Trello] Oops! Failed to register the webhook: URL (http://foobar.com:789/redmine/trello_webhooks.json) did not return 200 status code, got 403`

`Redirected to http://localhost:789/redmine/projects/git-scripts/trello_card_sync/mappings
Completed 302 Found in 975ms (ActiveRecord: 46.0ms)`

`Started GET "/redmine/projects/git-scripts/trello_card_sync/mappings" for 127.0.0.1 at 2018-03-26 17:29:25 -0700`

`Processing by MappingsController#index as HTML
  Parameters: {"project_id"=>"git-scripts"}
  Current user: admin (id=1)
  Rendered plugins/redmine_trello_card_sync/app/views/mappings/_bidirectional_sync.html.erb (1.0ms)
  Rendered plugins/redmine_trello_card_sync/app/views/mappings/index.html.erb within layouts/base (965.9ms)`

`[Trello] Is TrelloCardSync plugin ready? true
  Rendered inline template (1.0ms)`

`Completed 200 OK in 2751ms (Views: 2151.5ms | ActiveRecord: 106.1ms)`

`Started GET "/redmine/trello_webhooks.json" for 24.56.255.41 at 2018-03-26 17:29:44 -0700`

`Processing by TrelloWebhooksController#index as JSON
  Current user: anonymous`

`Completed 200 OK in 20ms (Views: 0.2ms | ActiveRecord: 1.0ms)`

`Started GET "/redmine/" for 172.56.42.99 at 2018-03-26 17:31:23 -0700`

`Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (5.0ms)
  Rendered inline template (0.0ms)`

`Completed 200 OK in 131ms (Views: 66.8ms | ActiveRecord: 31.0ms)`

`Started GET "/redmine/" for 172.56.42.99 at 2018-03-26 17:31:34 -0700`

`Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (7.0ms)
  Rendered inline template (1.0ms)`

`Completed 200 OK in 150ms (Views: 55.9ms | ActiveRecord: 36.0ms)`

`Started GET "/redmine/trello_webhooks.json" for 24.56.255.41 at 2018-03-26 20:51:24 -0700`

`Processing by TrelloWebhooksController#index as JSON
  Current user: anonymous
Completed 200 OK in 6ms (Views: 0.5ms | ActiveRecord: 1.0ms)`

**Comment by mafuchi** [comment]
@hiroshiyui Do you need any other information for this bug report?  This issue is still present.

**Comment by hiroshiyui** [comment]
@mafuchi I am sorry to tell you that I have resigned from this company on Mar 30, I have to set up a new environment for my Redmine development life :sweat_smile: and I will keep fixing this issue soon.

BTW, are you able to do 'one-way sync' (from Redmine to Trello) by this plugin? I want to make sure that the very basic feature is work for you.

**Comment by hiroshiyui** [comment]
@mafuchi Hello, here comes some updates, please give 1.1.4 (from my repo: https://github.com/hiroshiyui/redmine-trello-card-sync) a try.

BTW, I am wonder your internet facing Redmine installation is on port `789` or on the regular port `80`?

**Comment by mafuchi** [comment]
- I have attempted an update, but I am getting a weird error:
![plugins workflow](https://user-images.githubusercontent.com/6242892/38339435-0b32f866-3823-11e8-81d5-1a06eb7236f9.png)
It thinks it's still an older version from the original fork. 
- I can access the config page, but if I attempt to create a two-way link I get a 503 error (I'm using https).  It also seems to have issue with my self signed cert (it's just for my usage)
`[Trello] Bidirectional sync is enabled
[Trello] Creating webhook for '[foo-bar]' ([ID_here])
[Trello] Oops! Failed to register the webhook: URL (https://foo.bar/redmine/trello_webhooks.json) not reachable. Error: self signed certificate
Redirected to http://localhost/redmine/projects/git-scripts/trello_card_sync/mappings
Completed 302 Found in 3928ms (ActiveRecord: 26.0ms)`
- For my port, I have to use non-standards, so I have chosen a random port for redmine.

**Comment by hiroshiyui** [comment]
@mafuchi 

Please use Let's Encrypt certificate if you want HTTPS, or just plain HTTP is sufficient. It doesn't matter whether HTTPS or HTTP for Trello Webhook, but you might not use a self-signed certicate, it can't pass on the Trello server-side.

I have a fresh Redmine installation and this plugin works as expected both one-way or bi-directional sync. Maybe there is something wrong on your system setup, such as firewall, or you have something like Nginx as the reverse proxy server in front of your Redmine application server?

**Comment by CKhouili** [comment]
@hiroshiyui Hello 

I'm running redmine on a docker container using this image : https://github.com/sameersbn/docker-redmine
The redmine container includes an Nginx and is also linked to a PostgreSQL container.

I filled all the informations in the Trello Card Sync Settings and I put http://localhost:10083/trello_webhooks.json on the Trello Webhooks Endpoint URL but i'm getting Error status 503 when I try to enable the Bidirectional Sync, you will find below the production.log related to this error :

[Trello] Bidirectional sync is enabled
[Trello] Creating webhook for 'test redmine' (5b03db5bea0f6060b0c379b1)
[Trello] Oops! Failed to register the webhook: URL (http://localhost:10083/trello_webhooks.json) did not return 200 status code, got 503

Any help would be greatly appreciated

**Comment by hiroshiyui** [comment]
@CKhouili Webhook URL should be global, public accessible, `localhost` is not for it, though.

**Comment by CKhouili** [comment]
Hi @hiroshiyui 

Thank you for your quick response.

I changed the URL for a public one, it works fine

But when I want to sync a Trello card to redmine ( the issue is not already created in redmine), nothing happens and I get this error in the production.log

**Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.6ms)

NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/redmine_trello_card_sync/app/controllers/trello_webhooks_controller.rb:26:in `update_redmine_issue'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'**

Even if i want to sync a card from trello to an existing redmine issue, it returns 200 Ok and nothing is synchronized 

Thanks again for your time

**Comment by henrikek** [comment]
Hello, 
I also get the same problem when trying to create a new trello card that gets 500 Internal Server Error in redmine when a new Issue should be added.

NoMethodError (undefined method `[]' for nil:NilClass):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

I am using Redmine version 3.1.6 and the Trello card sync plugin version 1.1.3

I'm not a specialist at ruby so I'm not sure where to start debugging, is there anyone who has any suggestions for a solution?

**Comment by LeeXun** [comment]
Hi @henrikek,
Please try to update your redmine version and check your other environment. 
**Environment:**
Redmine version 3.4.4.stable
Ruby version 2.3.3-p222 (2016-11-21) [i386-mingw32]
Rails version 4.2.8
Environment production
Database adapter Mysql2
You can find this reference from the [first comment in this issue](https://github.com/KKBOX/redmine-trello-card-sync/issues/19#issue-307427323).

**Comment by LeeXun** [comment]
As [this comment](https://github.com/KKBOX/redmine-trello-card-sync/issues/19#issuecomment-378109619), I am sorry to say that we don't have maintainer for this project now.
To contact the author, please check [this project](https://github.com/hiroshiyui/redmine-trello-card-sync).
