### ISSUE TITLE
add documentation (readme seems incomplete)

### ISSUE THREAD

**Issue by Asenar** [KKBOX/redmine-trello-card-sync#3]
Hi,

your plugin seems great but I can't make it works.

What I did so far : 

- `mv plugins/redmine-trello-card-sync plugins/redmine_trello_card_sync`
- filled the inputs from `/settings/plugin/redmine_trello_card_sync` :
-- for «Trello API public key», I used my my app_key from https://trello.com/1/appKey/generate
-- for «Trello API member token», I tried my app_secret (also from https://trello.com/1/appKey/generate ), but that didn't worked. Then I tried the token got from `https://trello.com/1/authorize?expiration=never&name=SinglePurposeToken&key=REPLACEWITHYOURKEY`  (see https://developers.trello.com/authorize )
- I also added my trello username in `/my/account` page (this isn't mentionned anywhere)
- I also added the board id in the project settings general page.

What do I miss ?

**Comment by hiroshiyui** [comment]
@Asenar I've updated README.md for a better clear description. How about take a look at your `log/production.log` to provide related information for debugging? Thanks!

**Comment by Asenar** [comment]
I checked it yesterday and it gives no information.

I don't really know ruby language, so if there is a more verbose mode I didn't find it.

Also, about the redmine statuses, is that the «name» or the statuses_id I can find in the db ?

Do you confirm than when I create a redmine task, a corresponding card should be created ? Or is there something to do elsewhere ?

I would like to give you more information but I have absolutely no clue about what to check


Also, for the trello target list, should I use names or id (I used the `show_list_for_boards` script from https://github.com/cprice404/redmine-trello to find them)

**Comment by hiroshiyui** [comment]
Hello @Asenar,

Both Redmine statuses & Trello list are names, not IDs, maybe I will improve the mapping UI someday, sorry for your inconvenience.

By what my codes does, once you create or update a Redmine issue & its status is matched a mapping rule, your can see the corresponding Trello card in the list immediately.

**Comment by hiroshiyui** [comment]
Hello @Asenar,

I had a fresh Redmine installation with this plugin yesterday, I tried to follow the documents to do a step-by-step work and found no issue. I will close this issue, if you have any concern, you are welcome to re-open it.
