### ISSUE TITLE
Cannot update trello board.

### ISSUE THREAD

**Issue by satishsahani33** [KKBOX/redmine-trello-card-sync#6]
Hi,
I have configure redmine trello card syn plugin in my project. But I am not able to update my trello board.
Please suggest solutions.

**Comment by VictorRillo** [comment]
I have just implement it, and it´s happening to me too.

**Comment by hiroshiyui** [comment]
Hello,

Do you have any log for a reference?

**Comment by VictorRillo** [comment]
I ´ve search in the log and there is no reference about the plugin, errors neither.

**Comment by VictorRillo** [comment]
It´s the  log when I create a new Issue in Redmine:

`Started GET "/projects/prueba/issues/new" for 172.17.0.1 at 2017-06-08 06:39:49 +0000
Processing by IssuesController#new as HTML
  Parameters: {"project_id"=>"prueba"}
  Current user: vrillo (id=5)
  Rendered issues/_form_custom_fields.html.erb (4.2ms)
  Rendered issues/_attributes.html.erb (19.9ms)
  Rendered issues/_form.html.erb (24.9ms)
  Rendered attachments/_form.html.erb (4.0ms)
  Rendered issues/new.html.erb within layouts/base (30.5ms)
Completed 200 OK in 110ms (Views: 48.4ms | ActiveRecord: 33.9ms)
Started POST "/projects/prueba/issues" for 172.17.0.1 at 2017-06-08 06:39:59 +0000
Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"cYg6voHKm9D1eUHQgwXOCXpx2jKw+FIAGQzqQQyridFTME0qpejk0P13AfpEIKPTUrucLXAe6wkO3nW3yzi5Sw==", "form_update_triggered_by"=>"", "issue"=>{"tracker_id"=>"1", "subject"=>"petition", "description"=>"", "status_id"=>"1", "priority_id"=>"2", "assigned_to_id"=>"5", "parent_issue_id"=>"", "start_date"=>"2017-06-08", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0"}, "was_default_status"=>"1", "commit"=>"Crear", "project_id"=>"prueba"}
  Current user: vrillo (id=5)
  Rendered mailer/_issue.text.erb (3.4ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (3.9ms)
  Rendered mailer/_issue.html.erb (2.0ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (2.7ms)
Redirected to http://localhost:12345/issues/5
Completed 302 Found in 223ms (ActiveRecord: 134.3ms)
Started GET "/issues/5" for 172.17.0.1 at 2017-06-08 06:40:00 +0000
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"5"}
  Current user: vrillo (id=5)
  Rendered issues/_action_menu.html.erb (2.4ms)
  Rendered issue_relations/_form.html.erb (1.0ms)
  Rendered issues/_relations.html.erb (1.6ms)
  Rendered issues/_action_menu.html.erb (3.5ms)
  Rendered issues/_form_custom_fields.html.erb (0.0ms)
  Rendered issues/_attributes.html.erb (24.8ms)
  Rendered issues/_form.html.erb (37.3ms)
  Rendered attachments/_form.html.erb (1.6ms)
  Rendered issues/_edit.html.erb (52.0ms)
  Rendered issues/_sidebar.html.erb (5.5ms)
  Rendered issues/show.html.erb within layouts/base (91.9ms)
Completed 200 OK in 250ms (Views: 105.3ms | ActiveRecord: 63.5ms)`

**Comment by hiroshiyui** [comment]
@Basajarau did you found any log like `[Trello] Is TrelloCardSync plugin ready?`?

**Comment by VictorRillo** [comment]
These are the references that I found about that words.

152:[Trello] Is TrelloCardSync plugin ready? false
3801:[Trello] Is TrelloCardSync plugin ready? false
4100:[Trello] Is TrelloCardSync plugin ready? false

Never gets true.

**Comment by hiroshiyui** [comment]
@Basajarau maybe some of your setting values in `/settings/plugin/redmine_trello_card_sync` is invalid, would you please to help me to ensure them?

**Comment by VictorRillo** [comment]
Where is settings? I dont have that folder in the main route.
These are my folders:

4.0K -rw-rw-r--  1 redmine redmine  241 Apr  9 08:47 CONTRIBUTING.md
4.0K -rw-rw-r--  1 redmine redmine 3.9K Apr  9 08:47 Gemfile
8.0K -rw-r--r--  1 root    root    5.4K Jun  7 08:14 Gemfile.lock
4.0K -rw-rw-r--  1 redmine redmine  205 Apr  9 08:47 README.rdoc
4.0K -rw-rw-r--  1 redmine redmine  275 Apr  9 08:47 Rakefile
4.0K drwxrwxr-x  6 redmine redmine 4.0K Apr  9 08:46 app
4.0K -rw-rw-r--  1 redmine redmine  851 Apr  9 08:47 appveyor.yml
4.0K drwxrwxr-x  2 redmine redmine 4.0K Apr  9 08:47 bin
4.0K drwxrwxr-x  1 redmine redmine 4.0K Jun  7 07:47 config
4.0K -rw-rw-r--  1 redmine redmine  160 Apr  9 08:47 config.ru
4.0K drwxrwxr-x  1 redmine redmine 4.0K Jun  7 07:47 db
4.0K drwxrwxr-x  2 redmine redmine 4.0K Apr  9 08:47 doc
4.0K drwxrwxr-x  5 redmine redmine 4.0K Apr  9 08:47 extra
4.0K drwxr-xr-x  2 redmine redmine 4.0K Jun  7 07:47 files
4.0K drwxr-xr-x  3 root    root    4.0K Jun  7 07:47 htdocs
4.0K drwxrwxr-x  7 redmine redmine 4.0K Apr  9 08:47 lib
4.0K drwxr-xr-x  1 redmine redmine 4.0K Jun  7 07:47 log
4.0K drwxrwxr-x  1 redmine redmine 4.0K Jun  7 07:47 plugins
4.0K drwxrwxr-x  1 redmine redmine 4.0K Apr  9 08:47 public
4.0K drwxrwxr-x  2 redmine redmine 4.0K Apr  9 08:47 script
4.0K drwxrwxr-x 10 redmine redmine 4.0K Apr  9 08:46 test
4.0K drwxr-xr-x  1 redmine redmine 4.0K Jun  7 07:47 tmp
4.0K drwxrwxr-x  2 redmine redmine 4.0K Apr  9 08:47 vendor
4.0K -rwxr-xr-x 1 root root  880 Mar 21 17:50 init.rb
4.0K drwxr-xr-x 3 root root 4.0K Mar 21 17:50 lib
4.0K drwxr-xr-x 2 root root 4.0K Mar 21 17:50 test

**Comment by hiroshiyui** [comment]
@Basajarau Sorry it's URI, not path of file system. Did you followed `README.md` to configure this plugin?

**Comment by VictorRillo** [comment]
The only thing that I didn´t was to clone the plugin outside the Redmine installation.

And when I was doing the  `bundle install --without development test` i got an error and I had to install development tools:
sudo apt-get update
sudo apt-get install build-essential

Maybe the issue is caused because of something of these things?

**Comment by hiroshiyui** [comment]
@Basajarau I guess that maybe you have entered the invalid Trello API public key & Trello API member token, the first is 32 characters long while the second is 64 characters long.

**Comment by VictorRillo** [comment]
It´s Ok.

**Comment by VictorRillo** [comment]
The Trello API member token is taken from here:
https://trello.com/1/token/approve

what i see is:
 You have granted access to your Trello information.

To complete the process, please give this token: 

<THE KEY>

Is it the correct?

**Comment by hiroshiyui** [comment]
@Basajarau Yes it is.

**Comment by Basajarau** [comment]
I have tried the new versión now I get this:
279:[Trello] Is TrelloCardSync plugin ready? true
But it´s not syncronized.

It´s the full log when I create an issue:

> Started GET "/projects/prueba/issues/new" for 172.17.0.1 at 2017-06-09 06:53:24 +0000
Processing by IssuesController#new as HTML
  Parameters: {"project_id"=>"prueba"}
  Current user: vrillo (id=5)
  Rendered issues/_form_custom_fields.html.erb (2.8ms)
  Rendered issues/_attributes.html.erb (14.6ms)
  Rendered issues/_form.html.erb (19.4ms)
  Rendered attachments/_form.html.erb (1.5ms)
  Rendered issues/new.html.erb within layouts/base (22.5ms)
Completed 200 OK in 129ms (Views: 37.6ms | ActiveRecord: 60.3ms)
Started POST "/projects/prueba/issues" for 172.17.0.1 at 2017-06-09 06:53:39 +0000
Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"4ZouwRgeiTNJkmGAtxXVZqTPpVslzf4xTYYacfHmrFoKNjlu+FmO7gJs2aYUB4G6IyeTO1mee/b3N1ZuVB8bRw==", "form_update_triggered_by"=>"", "issue"=>{"tracker_id"=>"1", "subject"=>"Issue", "description"=>"1111", "status_id"=>"1", "priority_id"=>"2", "assigned_to_id"=>"5", "parent_issue_id"=>"", "start_date"=>"2017-06-09", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0"}, "was_default_status"=>"1", "commit"=>"Create", "project_id"=>"prueba"}
  Current user: vrillo (id=5)
  Rendered mailer/_issue.text.erb (2.5ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (3.7ms)
  Rendered mailer/_issue.html.erb (3.0ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (3.6ms)
Found invalid list in plugin settings: In progress
Redirected to http://localhost:5252/issues/3
Completed 302 Found in 870ms (ActiveRecord: 321.0ms)
Started GET "/issues/3" for 172.17.0.1 at 2017-06-09 06:53:40 +0000
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"3"}
  Current user: vrillo (id=5)
  Rendered issues/_action_menu.html.erb (2.8ms)
  Rendered issue_relations/_form.html.erb (1.2ms)
  Rendered issues/_relations.html.erb (1.8ms)
  Rendered issues/_action_menu.html.erb (2.3ms)
  Rendered issues/_form_custom_fields.html.erb (0.1ms)
  Rendered issues/_attributes.html.erb (8.7ms)
  Rendered issues/_form.html.erb (19.5ms)
  Rendered attachments/_form.html.erb (1.6ms)
  Rendered issues/_edit.html.erb (31.5ms)
  Rendered issues/_sidebar.html.erb (4.0ms)
  Rendered issues/show.html.erb within layouts/base (65.6ms)
Completed 200 OK in 241ms (Views: 69.5ms | ActiveRecord: 86.4ms)

**Comment by VictorRillo** [comment]
I´ve installed the new versión and it continues without working, I have seen the error in the log (invalid key), I copy it to you:

> Started POST "/projects/prueba/issues" for 172.17.0.1 at 2017-06-09 07:05:06 +0000
Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"oEcweU++SkppCAxaEgvJuYLxOTDJJ/qdFcAbI0MaUUSLKhs1MO2FjQU+X7rsGy1kBhEz/+Aiuhs68dYI4YaWWA==", "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0", "tracker_id"=>"1", "subject"=>"a", "description"=>"aaaaaaaaaaaaaaa", "status_id"=>"1", "priority_id"=>"2", "assigned_to_id"=>"5", "parent_issue_id"=>"", "start_date"=>"2017-06-09", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0"}, "was_default_status"=>"1", "commit"=>"Crear", "project_id"=>"prueba"}
  Current user: admin (id=1)
  Rendered mailer/_issue.text.erb (3.1ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (3.6ms)
  Rendered mailer/_issue.html.erb (2.9ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (3.4ms)
[Trello] Status mapping: 'New' -> 'Task backlogs'
[Trello] Processing card: #6 a
invalid key
Redirected to http://localhost:5252/issues/6
Completed 302 Found in 1613ms (ActiveRecord: 123.2ms)
Started GET "/issues/6" for 172.17.0.1 at 2017-06-09 07:05:08 +0000
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"6"}
  Current user: admin (id=1)
  Rendered issues/_action_menu.html.erb (13.5ms)
  Rendered issue_relations/_form.html.erb (3.2ms)
  Rendered issues/_relations.html.erb (4.2ms)
  Rendered issues/_action_menu.html.erb (2.7ms)
  Rendered issues/_form_custom_fields.html.erb (0.1ms)
  Rendered issues/_attributes.html.erb (41.1ms)
  Rendered issues/_form.html.erb (65.4ms)
  Rendered attachments/_form.html.erb (1.5ms)
  Rendered issues/_edit.html.erb (94.4ms)
  Rendered issues/_sidebar.html.erb (8.2ms)
  Rendered watchers/_watchers.html.erb (5.7ms)
  Rendered issues/show.html.erb within layouts/base (182.5ms)
Completed 200 OK in 353ms (Views: 203.2ms | ActiveRecord: 97.1ms)

**Comment by hiroshiyui** [comment]
@Basajarau consider the `invalid key` in logs, please ensure that you entered the valid key & token.

**Comment by VictorRillo** [comment]
Trello API public key (https://trello.com/app-key):
![imagen](https://user-images.githubusercontent.com/24370613/26965219-1141091a-4cf5-11e7-9a2f-eefead41d266.png)

Trello API member token (https://trello.com/1/token/approve):
![imagen](https://user-images.githubusercontent.com/24370613/26965280-5587f3c2-4cf5-11e7-94bd-e8a9b3dba3e4.png)

Trello key:
https://trello.com/b/{KEY}/tablero-de-bienvenida

**Comment by hiroshiyui** [comment]
@Basajarau please help me to test the latest updated code to see if it resolves your issue. 🙇

**Comment by VictorRillo** [comment]
Ok, its gonna take me 2-3 hours more or less I have a meeting, thanks for all the support!

**Comment by satishsahani33** [comment]
I uninstall and then re install plugin and it worked.
Thanks for your support @hiroshiyui

**Comment by VictorRillo** [comment]
It´s working, thank you very much!
🥇

**Comment by satishsahani33** [comment]
Currently the syncing is one way i.e. when we changes in redmine dashboard it is reflected in trello board.
Is it possible to update redmine dashboard after updating statuses in trello board?

**Comment by hiroshiyui** [comment]
@satishsahani10 Good question, actually I am working on bi-directional syncing, it's more difficult and needs much time to be implemented.

**Comment by satishsahani33** [comment]
Best of luck in advance @hiroshiyui. You are doing a great job. Please let me know once you success.
Thanks for your effort.

**Comment by VictorRillo** [comment]
Yes, I will wait for it, good job guy!
