### ISSUE TITLE
install issue on bitnami redmine docker container

### ISSUE THREAD

**Issue by aries0324** [KKBOX/redmine-trello-card-sync#9]
Hi, 
I want to install redmine-trello card sync on bitnami redmine docker container.
Following the steps in readme, I have finished "Run `bundle install --without development test` to install essential gems.".
But I got error in next step, Run `bundle exec rake db:migrate_plugins RAILS_ENV=production`.
The error message is as below.
    rake aborted!
    No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
    (See full trace by running task with --trace)
Am I miss anything?
Please give me some suggestion.
Thank you.

**Comment by hiroshiyui** [comment]
@aries0324 Would you please give me the full steps you did before? I don't have any experience about to install Redmine in a Docker container, though.

**Comment by aries0324** [comment]
I install redmine docker from https://bitnami.com/stack/redmine/installer.
It just some simple clicks to finish redmine and linux install.
Then I just use ocker command to install your plugin into redmine on docker.

**Comment by aries0324** [comment]
Hi, I pull another docker file and tried to install your plugin.
I can install plugin successful.
But there is no trello card created after I created new issue on redmine.
I setup redmine status as below.
New,In Progress,Resolved,Feedback,Closed
And I setup trello list as below.
New,In Progress,Resolved,Feedback,//close

In trello, I create a list named "New".
But I created a new issue in redmine, I don't find new card created in trello.
Is there anything I need to check?
Please give me some hint. Thank you.

**Comment by hiroshiyui** [comment]
@aries0324 Hello, did you select the target Trello board at the pull down list 'Target Trello board'?

**Comment by aries0324** [comment]
Yes. I have select target board. The board name is composed with Chinese and "&". Will this cause issue?

**Comment by aries0324** [comment]
BTW, I can see all the trello boards in the pull down list.

**Comment by hiroshiyui** [comment]
@aries0324 Good, that means you are able to call Trello APIs.

In your Redmine's top directory, please run `cat log/production.log` to get the related logs for me. It would be better to show me only the recent logs, not to dump all to me, if you are unsure what 'recent logs' are, the last 50 logs may be good enough.

**Comment by aries0324** [comment]
Hi, please check attachment.

[product.zip](https://github.com/KKBOX/redmine-trello-card-sync/files/1130481/product.zip)

**Comment by hiroshiyui** [comment]
@aries0324 Excuse me, I can't find anything helpful in this log file, may be you can do some actions like to open & update an issue, thus your Redmine will generate some related logs because this plugin would do something.

**Comment by aries0324** [comment]
Hi, I found one line in this log.
"Found invalid list in plugin settings: In Progress"
I do the following tests.
1. remove space: "InProgress" --> failed
2. keep only one status in setting: New. I can see a new card insert to the board. --> pass.
Any idea about this case?
Thank you.

**Comment by hiroshiyui** [comment]
@aries0324 Besides "In Progress", does other issue names & list names working as expected?

**Comment by aries0324** [comment]
Now, only one item in the list will work. More than one item in the list will cause issue.

**Comment by hiroshiyui** [comment]
@aries0324 did you input your Trello list names manually or by copy-and-paste?

**Comment by aries0324** [comment]
I use copy and paste.
After I remove and input manually again.
It' works now.
Thank you.

**Comment by aries0324** [comment]
One more question once I update comment in redmine.
Will this be sync to trello?
Thank you.

**Comment by hiroshiyui** [comment]
@aries0324 Great. Comment synchronization is not in my road map, because my team doesn't  have this feature requirement. However, your code patches are welcomed. 🙇
